Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/SymbolArray:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

AllCops:
  TargetRubyVersion: 3.0.0
  Exclude:
    - 'config/initializers/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/*'
    - 'tmp/**/*'
    - 'public/**/*'
    - 'log/*'

Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
